version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: split-control-app
    container_name: split-control-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
    networks:
      - splitnet
    env_file:
      - .env
    depends_on:
      - web

  web:
    image: nginx:1.25-alpine
    container_name: split-control-web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - splitnet
    depends_on:
      - app

networks:
  splitnet:
    driver: bridge
